services:
  web:
    build: .
    ports:
      - "8081:80" # Tu app estará disponible en http://localhost:8081 en la compu de tus invitados
    volumes:
      - .:/var/www/html/ # Sincroniza el código para que al editar un archivo se refleje de inmediato
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=sistema_comanda_digital_v1
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306" # Puerto de MySQL en el host (3307 para evitar chocar con XAMPP)
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sistema_comanda_digital_v1
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d # La primera vez que se levanta, lee aquí y crea tu BD original
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
